services:
  ny-taxi-data:
    container_name: ny-taxi-data
    image: postgres:18.1-alpine3.22
    ports:
      - 5432:5432
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

volumes:
  data:
