services:
  ny-taxi-data:
    container_name: ny-taxi-data
    image: postgres:18.1-alpine3.22
    ports:
      - 5432:5432
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
  jupiter:
    container_name: jupiter
    image: eipdev/alpine-jupyter-notebook
    ports:
      - 80:8888
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /notebooks:/opt/notebook
